#! /bin/sh

. $(dirname $0)/util.inc

function usage
{
    echo "kernel config is required to compile"
    echo "Usage:"
    echo -e "\t$ ./$(basename "$0") PATH"
}

function validate_kernel_config
{
    if [ "$1" == "--help" ]; then
        return 1
    fi

    if [ $# -lt 1 ]; then
        return 1
    fi

    # validate existing file
    if [[ ! -f $1 ]]; then
        echo "'$1' is not a valid file"
        return 1
    fi

    # validate file
    if [[ ! -f $1 ]]; then
        echo "'$1' is not a valid file"
        return 1
    fi

    # all ok
    KERNEL_CONFIG=$1
    return 0
}

function compile_kernel_and_install
{
    validate_kernel_config $*
    if [ $? -ne 0 ]; then
        usage
        exit 1
    fi

    pushd "$PWD"
    echo "using config: " $KERNEL_CONFIG
    cd /usr/src/linux

    /usr/bin/genkernel \
        --makeopts=-j$AVAILABLE_CPUS \
        --kernel-config=$KERNEL_CONFIG all \
    && /usr/sbin/grub-install /dev/sda

    popd

# make -s -j8 1>/tmp/kernel.log \
#  && make modules_install \
#  && genkernel --install initramfs \
#  && cp -v ./arch/x86_64/boot/bzImage /boot/kernel-$(uname -r) \
#  && /sbin/lilo
}

function update_grub_entries
{
    /usr/sbin/grub-mkconfig -o /boot/grub/grub.cfg
}

function build_kernel_dependent_application_modules
{
    PACKAGE_NAME=$1
    shift

    if [[ -z $PACKAGE_NAME ]]; then
        echo "missing package name"
        exit 1
    fi

    NOT_INSTALLED_MSG="No matches found"
    PACKAGE_INSTALLED=$(eix -Ic $PACKAGE_NAME)

    if [ "$PACKAGE_INSTALLED" == "$NOT_INSTALLED_MSG" ]; then
        return
    fi

    echo "installing '$PACKAGE_NAME' ..."

    if ! emerge -1 $PACKAGE_NAME ; then
        echo "failed"
        exit 1
    fi
}

# TODO (kgaipal): make invokation from commment line based on options
compile_kernel_and_install $1
update_grub_entries
build_kernel_dependent_application_modules app-emulation/virtualbox-modules
build_kernel_dependent_application_modules net-wireless/broadcom-sta
build_kernel_dependent_application_modules sys-firmware/b43-firmware
