#!/bin/bash

CSCOPE_FILE=cscope.files

function usage
{
    echo "Usage:"
    echo -e "\t$ ./$(basename $0) PATH"
    echo -e "\n\tBuilds a files list for cscope program in PATH/$CSCOPE_FILE"
}

function validate
{
    if [ "$1" == "--help" ]; then
        return 1
    fi

    if [ $# -lt 1 ]; then
        return 1
    fi

    # all ok
    CSCOPE_PATH=$1
    return 0
}

function generate_cscope
{
    echo -n "building cscope files in $CSCOPE_PATH... "
    pushd $CSCOPE_PATH > /dev/null

    findk -type f \( \
          -name *.cpp \
          -o -name *.cc \
          -o -name *.cs \
          -o -name *.hpp \
          -o -name *.c \
          -o -name *.h \
          \) -printf "\"%p\"\n" \
          > $CSCOPE_FILE

    # remove some unwanted folders
    sed -i '/[Tt]est[[:alnum:]_\-]*/d' $CSCOPE_FILE

    popd > /dev/null

    echo "done."
}

validate $*
if [ $? -ne 0 ]; then
    usage
    exit 1
fi

generate_cscope
